### ISSUE TITLE
Adding action to keepStateFragment

### ISSUE THREAD

**Issue by sgupadya** [STAR-ZERO/navigation-keep-fragment-sample#1]
Is there a way to use both `<fragment>` tag and `<keep_state_fragment>` in the same navigation file. 
Also, the `<action>` tag under `<keep_state_fragment>`  is creating crashes with the message: "navigation destination is unknown to this NavController". Is there any other way to add action to `<keep_state_fragment>`?

**Comment by STAR-ZERO** [comment]
You can use global action.
https://developer.android.com/topic/libraries/architecture/navigation/navigation-global-action

However It's difficult to handle fragment back stack. 😞

**Comment by STAR-ZERO** [comment]
FYI: I added sample that fragment in tab navigates to another fragment.

**Comment by sgupadya** [comment]
Thanks will try that.

They haven't resolved this handling back stack issue in alpha-9 version also. :(

**Comment by STAR-ZERO** [comment]
Let me close. If you have anything, please create issue again.
