### ISSUE TITLE
navigate from FragmentNavigator does more stuff than what implemented in keep state

### ISSUE THREAD

**Issue by dabitdev** [STAR-ZERO/navigation-keep-fragment-sample#12]
looks like all this logic will be ignored as soon as the keep state navigator is used:
- navOptions are ignored (animations)
- SingleTopReplacement logic
- FragmentNavigator.Extras logic (sharedElements)

**Comment by STAR-ZERO** [comment]
I know. This repository is just sample. You can change if you want.
