### ISSUE TITLE
Fragments overlaping

### ISSUE THREAD

**Issue by Chinmay-Kalmane** [STAR-ZERO/navigation-keep-fragment-sample#15]
When  I press on two tabs on the bottom nav at once, it loads the two fragments simultaneously which result in the fragments overlapping on each other. This does not happen if I remove the keep state fragment. How to resolve this with keep-state?

**Comment by STAR-ZERO** [comment]
Thanks for the report.

I fixed it. https://github.com/STAR-ZERO/navigation-keep-fragment-sample/commit/5b9d0978035a62b314de2ea214cd0b572228a420
Please use `FragmentTransaction.commitNow`.
