### ISSUE TITLE
This version of Android Studio cannot open this project, please retry with Android Studio 3.5 or newer.

### ISSUE THREAD

**Issue by Ktirumalsetty** [STAR-ZERO/navigation-keep-fragment-sample#18]
Build Error with Android studio 3.4.2

**Comment by bloooi** [comment]
change classpath 'com.android.tools.build:gradle:3.5.0-beta04' to classpath 'com.android.tools.build:gradle:3.4.2' in project build.gradle.
it works.

**Comment by STAR-ZERO** [comment]
Sorry, too late 🙇 
@JaeBeomLee Thanks for your answer 👍
