### ISSUE TITLE
BottomNav selection is not updated when start destination is changed

### ISSUE THREAD

**Issue by Chinmay-Kalmane** [STAR-ZERO/navigation-keep-fragment-sample#2]
When I change the start destination in the nav_graph to Dashboard or Notifications the bottom navigation still shows selection as home.

**Comment by STAR-ZERO** [comment]
Thank you for reporting. I fixed this issue. 
Please see the commit. https://github.com/STAR-ZERO/navigation-keep-fragment-sample/commit/7b70c432be0a98012117d5bb041b5fd251bdbf40
